# Generated by Django 6.0.6 on 2026-06-05 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p (HD)'), ('1080p', '1080p (Full HD)'), ('2k', '2K'), ('4k', '4K (Ultra HD)')], max_length=10)),
                ('date_of_publishing', models.DateField(default=django.utils.timezone.now)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
            ],
        ),
    ]
