# Generated by Django 6.0.6 on 2026-06-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videx_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageStatus',
        ),
    ]
