# Generated by Django 6.0.6 on 2026-06-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
