# Generated by Django 6.0.6 on 2026-06-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_alter_video_date_of_publishing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumb_nail',
            new_name='thumbnail',
        ),
    ]
